### ISSUE TITLE
CI/CD to PyPI

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-python-api#1]
Not sure if this is something you guys are interested in, but it's very easy to set up continuous deployment from this repo to PyPI, so you don't have to rebuild and upload manually. You just need to grab an API token from PyPI to use in a workflow `.yml` file. [Here's](https://github.com/talkinglibrary/talklib/blob/main/.github/workflows/python-app.yml) one I set up recently (move down to the build and deploy section). To update it, you just increment the `version` in your `pyproject.toml` file and it will update on PyPI within a few seconds.

If you're interested, I'm happy to submit a PR to get it rolling! Cheers

**Comment by VictoriqueMoe** [comment]
> Not sure if this is something you guys are interested in, but it's very easy to set up continuous deployment from this repo to PyPI, so you don't have to rebuild and upload manually. You just need to grab an API token from PyPI to use in a workflow `.yml` file. [Here's](https://github.com/talkinglibrary/talklib/blob/main/.github/workflows/python-app.yml) one I set up recently (move down to the build and deploy section). To update it, you just increment the `version` in your `pyproject.toml` file and it will update on PyPI within a few seconds.
> 
> If you're interested, I'm happy to submit a PR to get it rolling! Cheers

that would be very good. i think @nakedmcse what do you think? I also think that it would be good to set up automatic deploymnet to npm for this repo https://github.com/waifuvault/waifuVault-node-api there is info here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry but i don't really get it

**Comment by weddleben** [comment]
> >
> I also think that it would be good to set up automatic deploymnet to npm for this repo https://github.com/waifuvault/waifuVault-node-api there is info here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry but i don't really get it


I think [this](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) is a better explanation of automatic deployment to npm

**Comment by VictoriqueMoe** [comment]
> > > 
> > 
> > 
> > I also think that it would be good to set up automatic deploymnet to npm for this repo https://github.com/waifuvault/waifuVault-node-api there is info here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry but i don't really get it
> 
> I think [this](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) is a better explanation of automatic deployment to npm

oh seems simple thanks

**Comment by nakedmcse** [comment]
Setting up automated deployment sounds good.  My concern is the key - password: ${{ secrets.PYPI_API_TOKEN }} - how is the API token secured ?

**Comment by weddleben** [comment]
I THINK the way it's typically done - and the way I did it in my other project linked above - is to store the API token as a "GitHub Secret" in the repo. Only repo admins/owners can set/view/edit Secrets. It's like an environment variable, and you access it within a GitHub Action with the syntax you mentioned:  `${{ secrets.PYPI_API_TOKEN }}`

One of you would need to create a token on PyPI and set it as a Secret in the repo before we could implement the GH Action.

![ss](https://github.com/waifuvault/waifuVault-python-api/assets/107364642/435f00fe-c526-4f88-bc5c-c8d2c380d100)

**Comment by weddleben** [comment]
Excellent! I will put together a draft yml for you and submit a PR here in a few hours

**Comment by nakedmcse** [comment]
I approved and merged your yaml.  I'm about to push a commit that updates the version to see what happens.

**Comment by nakedmcse** [comment]
Had to update the version number of the updater in the yaml, so you will need to sync your branch, but it works.
Thank you Ben.

![Screen Shot 2024-03-13 at 3 54 03 PM](https://github.com/waifuvault/waifuVault-python-api/assets/133156975/dd3fd0c5-e609-4243-92e3-0422d32b04e1)

**Comment by weddleben** [comment]
AH! I used `pypa/gh-action-pypi-publish@release/v1.x.x` when apparently the correct syntax for using a specific release tag is `pypa/gh-action-pypi-publish@v1.x.x`

either way, v1 is not deprecated for this action, so should be fine. thanks for catching that! i see the latest version was pushed to PyPI. Yay

closing the issue, thanks!
