### ISSUE TITLE
latest version didn't deploy

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-python-api#20]
it looks like the latest version with the new Restrictions functionality did not deploy to PyPi. 

<img width="1257" alt="Screen Shot 2024-08-25 at 5 15 00 PM" src="https://github.com/user-attachments/assets/1dcc8aed-af8a-4bc0-af0e-77b428ba6fe0">
<img width="1243" alt="Screen Shot 2024-08-25 at 5 18 20 PM" src="https://github.com/user-attachments/assets/1a254b24-2494-4194-b99d-5fb0c6e3df16">

**Comment by nakedmcse** [comment]
Fixed.  Thanks for pointing this out.
