### ISSUE TITLE
/dist

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-python-api#4]
does the `/dist` directory need to be added to `.gitignore`?

**Comment by VictoriqueMoe** [comment]
I would say yes but, i can't say for python @nakedmcse

**Comment by nakedmcse** [comment]
/dist needs to be uploadable, if you push manually.
I want to keep it in place.

**Comment by weddleben** [comment]
> /dist needs to be uploadable, if you push manually. I want to keep it in place.

I was just suggesting it may not need to be tracked in Git. Can still build it locally, if needed. But OK, sounds good!

**Comment by nakedmcse** [comment]
Closed
