### ISSUE TITLE
document exception for delete_file

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-python-api#5]
If an invalid token is passed to the `delete_file` function, an exception is raised. It may be good to mention this in the documentation, perhaps in the `Extra Info` column of the table?

This is per our [discussion](https://github.com/waifuvault/waifuVault-node-api/issues/5) in the Node SDK repo.

**Comment by weddleben** [comment]
in addition to updating the `Extra Info` column, maybe updating the example code snippet to something like this would be helpful

````python
import waifuvault

try:
    del_file = waifuvault.delete_file(token='notAValidToken')
    print(del_file)
except Exception as exc:
    print(exc)
````

**Comment by nakedmcse** [comment]
Documentation updated.
