### ISSUE TITLE
Documentation for Update File Info

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-python-api#6]
Question regarding the new [documentation](https://github.com/waifuvault/waifuVault-python-api?tab=readme-ov-file#update-file-info) for the `Update File Info` function. It says:  `If you have a token from your upload. Then you can get file info. This results in the following info:`

Should it say then you can `update` the file info, instead of `get` file info?

Also, in the param table, in the `password` row, should it say the `new` password of the file, instead of the `current` password? If not, what is the difference between `password` and `previous_password`?

**Comment by nakedmcse** [comment]
This was an oversight during development (the readme was incomplete).  It has been updated.
